### ISSUE TITLE
Roadmap for this repository [tracking]

### ISSUE THREAD

**Issue by PythonCoderAS** [flyboat-org/frontend#16]
- [ ] Setup dependabot
- [ ] Setup linting (prettier)
- [ ] Setup linting (ESLint)
- [ ] Setup build testing
- [ ] Setup staging deploys
- [ ] Setup production deploys
